export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const FETCH_NODES = 'FETCH_NODES';
export const FILTER_CONTENT_KIND = 'FILTER_CONTENT_KIND';
export const FILTER_TOPIC = 'FILTER_TOPIC';
export const FILTER_VISIBIITY = 'FILTER_VISIBIITY';
export const FIREBASE_FETCH_ONCE = 'FIREBASE_FETCH_ONCE';
