/* @flow */
export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const FETCH_NODES = 'FETCH_NODES';
export const FILTER_VISIBIITY = 'FILTER_VISIBIITY';
export const FIREBASE_WORKFLOW = 'FIREBASE_WORKFLOW';
export const FIREBASE_AUTH = 'FIREBASE_AUTH';
export const FIREBASE_ROLES = 'FIREBASE_ROLES';
export const FIREBASE_USERS = 'FIREBASE_USERS';
